### ISSUE TITLE
Does not work for bedrock / mobile players UNLESS they are operator?!

### ISSUE THREAD

**Issue by MarkHarrisMedia** [sylvxa/sswaystones#4] opened 2024-08-23 07:16 UTC
Does not work for bedrock / mobile players UNLESS they are operator?!

**Comment by sylvxa** [comment] 2024-08-23 12:58
This shouldn't be the case, can you explain the issue a little more?

**Comment by MarkHarrisMedia** [comment] 2024-08-23 22:38
I've tested it with both java / pc and mobile / bedrock. It worked perfect on java / pc whether I was operator or not. However, on mobile / bedrock, it worked if I was operator, but once /deopped myself, it would not let me click on the waystone, the gui would not open up. Since there is no permissions node to assign non opped users, it wont work for my server. Please help me fix this as your mod is exactly what I was looking for, I hope we can get it working right.

I even tried adding luckperms but cant find any permission nodes to assign nonopped users.

**Comment by sylvxa** [comment] 2024-08-24 15:01
I can't recreate this issue, can you post more about the server you are running? Do you have any sort of land protection mods, spawn protection, etc? Are there any errors in the console or chat?

Please post a mod list and check if the waystone is in any protected land.

**Comment by MarkHarrisMedia** [comment] 2024-08-24 15:34
There are not any protected land mods on my server. I will send mod list as
soon as I can.

**Comment by sylvxa** [comment] 2024-08-24 21:08
I tested it out and I would guess you are experiencing the effects of vanilla Minecraft's [spawn protection](https://minecraft.fandom.com/wiki/Spawn_protection). It won't let you interact with any blocks within the default 16 blocks, though that wouldn't explain why the Java account is still able to interact with the waystone. Try setting this to 0 in the `server.properties` and see if the issue is still occurring, and post your mod list if not. All I know is that there is *nothing in this mod adding a permission check to the waystone viewer*.

**Comment by MarkHarrisMedia** [comment] 2024-08-26 05:03
I appreciate that. It seems to be working now after restoring a backup and setting spawn protection to 0.

Thank you! I am excited to start using this mod.

**Comment by sylvxa** [comment] 2024-08-30 22:49
Closing!

**Closed by sylvxa** 2024-08-30 22:49 UTC
